services:
  redis:
    image: redis:7
    container_name: redis
    restart: always
    # DO NOT expose Redis in production
    # ports:
    #   - "6379:6379"

  greentrack:
    build:
      context: .
      dockerfile: Dockerfile
    image: carbon-tracker-api
    container_name: greentrack
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      SPRING_DATA_MONGODB_URI: ${MONGODB_URI}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    restart: always
